Taxonomy database
codeforamerica/civic-tech-taxonomy pull request #17
Opened 2021-05-14 20:06 UTC by giosce

Scripts to create MySQL database to hold taxonomy data.
Scripts to populate the database from the taxonomy toml files.

2021-05-14 21:02 UTC, themightychris requested changes
rename `database/` to `tools/mysql-loader`

2021-05-14 21:06 UTC, themightychris commented on database/brigade-index-and-taxonomy.sql
> +CREATE TABLE IF NOT EXISTS `projects_topics_copy` (
delete this?

2021-05-14 21:06 UTC, themightychris commented on database/brigade-index-and-taxonomy.sql
> +CREATE TABLE `taxonomy_view_2` (
delete?

2021-05-14 21:07 UTC, themightychris commented on database/proj-toml-2-mysql.py
> +              cursor.execute(sql, (project_id, topic_id))
should these `_2`s be here?

2021-05-24 00:31 UTC, giosce commented on database/proj-toml-2-mysql.py
> +              cursor.execute(sql, (project_id, topic_id))
Removed _2 tables/statements.

2021-05-24 00:32 UTC, giosce commented on database/brigade-index-and-taxonomy.sql
> +CREATE TABLE `taxonomy_view_2` (
Removed the temporary tables, but I still have taxonomy_view_2, I don't know a much better name.

2021-05-24 00:32 UTC, giosce commented on database/brigade-index-and-taxonomy.sql
> +CREATE TABLE IF NOT EXISTS `projects_topics_copy` (
Removed creation of _copy table.

2021-06-08 21:52 UTC, themightychris approved these changes

2021-06-08 21:52 UTC, merged